name: Node.js Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
       
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.KEY }}
          script: cd /projects/paycourse && git checkout . && git pull && npx yarn run build && rm -R /var/www/padar.uz/ && mkdir /var/www/padar.uz && cp -a build/. /var/www/padar.uz/